name: Build
# Complete packaging in the future

on: 
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
        # how to use macos ???

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Set up GCC
      if: matrix.os == 'ubuntu-24.04'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 14
        platform: x64

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Build with CMake
      run: cmake -B build -S . && cmake --build build
